// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGemMNzTg_fs7mmZNezKCMga2YjbBwRDQ',
    appId: '1:574259181819:web:4bb4495431e546bfe7985e',
    messagingSenderId: '574259181819',
    projectId: 'screms-application',
    authDomain: 'screms-application.firebaseapp.com',
    databaseURL: 'https://screms-application-default-rtdb.firebaseio.com',
    storageBucket: 'screms-application.appspot.com',
    measurementId: 'G-SNN8TYP3BY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ-O0jT6bLW-u2ekWe_RE-EILO8Mkyd7g',
    appId: '1:574259181819:android:bc92db2603f0a8d8e7985e',
    messagingSenderId: '574259181819',
    projectId: 'screms-application',
    databaseURL: 'https://screms-application-default-rtdb.firebaseio.com',
    storageBucket: 'screms-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNS57Pjau8YgUPOLC08WDes7CBDh0BjTc',
    appId: '1:574259181819:ios:9ec569a204b14f9de7985e',
    messagingSenderId: '574259181819',
    projectId: 'screms-application',
    databaseURL: 'https://screms-application-default-rtdb.firebaseio.com',
    storageBucket: 'screms-application.appspot.com',
    iosClientId: '574259181819-8nnhtmldme4qv874oba7r1ke3li37g9t.apps.googleusercontent.com',
    iosBundleId: 'com.screms.carrent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNS57Pjau8YgUPOLC08WDes7CBDh0BjTc',
    appId: '1:574259181819:ios:0aaa6829ff43c4a8e7985e',
    messagingSenderId: '574259181819',
    projectId: 'screms-application',
    databaseURL: 'https://screms-application-default-rtdb.firebaseio.com',
    storageBucket: 'screms-application.appspot.com',
    iosClientId: '574259181819-fd0gr816feqtt8td571hjlk4uknbqu2c.apps.googleusercontent.com',
    iosBundleId: 'com.screms.carrent.RunnerTests',
  );
}
